name: CICD Pipeline

on:
  push:
    branches:
      - main

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  TENOR_API: ${{ secrets.TENOR_API }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          TENOR_API: ${{ secrets.TENOR_API }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Ensure the directory exists
            mkdir -p /home/ubuntu/Syaa

            # Write the environment variables to the .env file
            echo "DISCORD_TOKEN=${DISCORD_TOKEN}" > /home/ubuntu/Syaa/.env
            echo "TENOR_API=${TENOR_API}" >> /home/ubuntu/Syaa/.env

            # Run the deployment script
            bash /home/ubuntu/deploy.sh
          EOF
